### ISSUE TITLE
Connection Lost from Server, reconnecting...

### ISSUE THREAD

**Issue by nxt-owner** [FantoX001/Atlas-MD#59]
#Error
![image](https://user-images.githubusercontent.com/91351974/225936077-8e333428-edb1-451c-8aa2-97e74d0b803b.png)

#what is the err? mongo cluster working fine 

![image](https://user-images.githubusercontent.com/91351974/225937009-abe899d1-5b36-438e-925b-99ffac850d7a.png)

#With white listed ip
![image](https://user-images.githubusercontent.com/91351974/225937358-4f620fc5-8d20-460e-a702-f1b7710ce24e.png)
#full error
```
Atlas MD Server Status => close
Connection Lost from Server, reconnecting...
MongoNetworkTimeoutError: connection timed out
    at connectionFailureError (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:389:20)
    at TLSSocket.<anonymous> (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:310:22)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket.Socket._onTimeout (node:net:550:8)
    at listOnTimeout (node:internal/timers:559:17) {
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(0) {}
} Promise {
  <rejected> MongoNetworkTimeoutError: connection timed out
      at connectionFailureError (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:389:20)
      at TLSSocket.<anonymous> (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:310:22)
      at Object.onceWrapper (node:events:627:28)
      at TLSSocket.emit (node:events:513:28)
      at TLSSocket.emit (node:domain:489:12)
      at TLSSocket.Socket._onTimeout (node:net:550:8)
      at listOnTimeout (node:internal/timers:559:17) {
    connectionGeneration: 0,
    [Symbol(errorLabels)]: Set(0) {}
  }
}
MongoNetworkTimeoutError: connection timed out
    at connectionFailureError (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:389:20)
    at TLSSocket.<anonymous> (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:310:22)
    at Object.onceWrapper (node:events:627:28)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket.Socket._onTimeout (node:net:550:8)
    at listOnTimeout (node:internal/timers:559:17) {
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(0) {}
} Promise {
  <rejected> MongoNetworkTimeoutError: connection timed out
      at connectionFailureError (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:389:20)
      at TLSSocket.<anonymous> (/home/runner/x/node_modules/mongodb/lib/cmap/connect.js:310:22)

Database 1 has been connected Successfully !


Database 2 has been connected Successfully !

Hint: hit control+c anytime to enter REPL.
(node:918) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be sw
```

**Comment by FantoX001** [comment]
![IMG_20230317_201818.jpg](https://user-images.githubusercontent.com/96835724/225938717-ea431f0e-ebb8-4f8f-9aea-e3863e96d6de.jpg)

At first check if you are using latest version (2.2) or not.

If you are using older version then update your repo.

Next, after updating/ syncing your GitHub repo got to Repl.it then from tools go to git option.

![IMG_20230317_202158.jpg](https://user-images.githubusercontent.com/96835724/225940056-4241aeb0-64f4-4b94-9701-08f3ea911943.jpg)


There you will get a sync option. Just click on it your Repl.it app will be updated automatically.

Next go to secrets and change the session id.

Then restart the bot. 

Issue should be fixed.

If you still get error after following these above steps. Don't hesitate to contact me again.

**Comment by nxt-owner** [comment]
> ## At first check if you are using latest version (2.2) or not.
> ![IMG_20230317_201818.jpg](https://user-images.githubusercontent.com/96835724/225938717-ea431f0e-ebb8-4f8f-9aea-e3863e96d6de.jpg)
> 
> * If you are using older version then update your repo.
> * Next, after updating/ syncing your GitHub repo got to Repl.it then from tools go to git option.
> 
> ![IMG_20230317_202158.jpg](https://user-images.githubusercontent.com/96835724/225940056-4241aeb0-64f4-4b94-9701-08f3ea911943.jpg)
> 
> * There you will get a sync option. Just click on it your Repl.it app will be updated automatically.
> * Next go to secrets and change the session id.
> * Then restart the bot.
> * Issue should be fixed.
> 
> ## If you still get error after following these above steps. Don't hesitate to contact me again.

Ok thanks im going to try that.
And i like to contribute this coolest thing with little updates by me 😊
